apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-chart.fullname" . }}
  labels:
    {{- include "service-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "service-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "service-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "service-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.nameOverride }}
          env:
            {{- range .Values.secretToFetch }}
            - name: {{ .envName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .kubeSecretName }}
                  key: {{ .secretKey }}
            {{- end }}
          {{- if .Values.envFromConfigMap }}
          envFrom:
            - configMapRef:
                name: {{ .Values.envFromConfigMap.name }}
                optional: true
          {{- end }}
        {{- if .Values.deployment.volumesMount }}
          volumeMounts:
            {{- toYaml .Values.deployment.volumesMount | nindent 12 }}
        {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            {{- if .Values.livenessProbe.tcp }}
            tcpSocket:
              port: {{ .Values.service.targetPort }}
            {{- end }}
            {{- if .Values.livenessProbe.exec }}
            exec:
              command:
                {{ .Values.livenessProbe.exec.command }}
            {{- end }}
          readinessProbe:
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            {{- if .Values.readinessProbe.tcp }}
            tcpSocket:
              port: {{ .Values.service.targetPort }}
            {{- end }}
            {{- if .Values.readinessProbe.exec }}
            exec:
              command:
                {{ .Values.readinessProbe.exec.command }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.volumes }}
      volumes:
      {{- toYaml .Values.deployment.volumes | nindent 8 }}
      {{- end }}
